name: Extraction

on:
  push:
    branches:
      - main

jobs:
  extract-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tesseract
        run: sudo apt install tesseract-ocr
      - name: Extract text from JPEG images
        run: for file in markdown/*.jpg; do tesseract $file "${file%.jpg}"; done
      - name: Commit output files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Extract text from JPEG images"
          add: "markdown/*.txt"